<?php echo($wo['reaction_name']) ?>
<div class="form-group form-float">
  <div class="form-line focused">
        <input type="file" class="form-control" name="imean">
        <label class="form-label">Reaction imean Theme Icon</label>
  </div>
</div>
<div class="form-group form-float">
  <div class="form-line focused">
        <input type="file" class="form-control" name="sunshine">
        <label class="form-label">Reaction Sunshine Theme Icon</label>
  </div>
</div>
<?php if ($wo['reaction_id'] < 7) { ?>
  <?php if (!empty($wo['imean_icon'])) { ?>
<label for="imean_to_use">Use Default Icon On imean Theme</label>
<div class="form-group">
    <input type="radio" name="imean_to_use" id="imean_to_use-enabled" value="1">
    <label for="imean_to_use-enabled">Default</label>
</div>
<?php } ?>
<?php if (!empty($wo['sunshine_icon'])) { ?>
<label for="sunshine_to_use">Use Default Icon On Sunshine Theme</label>
<div class="form-group">
    <input type="radio" name="sunshine_to_use" id="sunshine_to_use-enabled" value="1">
    <label for="sunshine_to_use-enabled">Default</label>
</div>
<?php } ?>
<?php } ?>
<input type="hidden" name="id" value="<?php echo($wo['reaction_id']) ?>">